### ISSUE TITLE
Isolate Webhook events that affect stock (race condition issue)

### ISSUE THREAD

**Issue by achadee** [vend/developer-wiki#6]
You guys trigger multiple webhook events per single action.
for example 
- product save triggers n + 1 events (n = number of variants)
- order create triggers product save and order create

Some suggestions:
- Don't trigger a product.update event when a sale has been made, It should be up to the developers to integrate all available webhooks to create a functioning system. Multiple events can cause race condition issues that are impossible to mitigate for. (Ive actually had to hard code sleep intervals in the vend integration so orders come before product updates and stock resolves correctly)
- Don't trigger product.update when consignments have been sent or received. Same issue as above

**Comment by pzurek** [comment]
There are a few "layers" to this suggestion. First, let's tackle the obvious:
- `product.update` triggered for a new sale:  
  That's not exactly true. When a sale happens 2 events are being triggered, `sale.update` and `inventory.update`. Sale, because obviously a sale was created and inventory because as a result of the sale the inventory has changed. No `product.update` should be happening. If you see it happening please let us know at api@vendhq.com.
- `product.update` triggered for a new consignment:  
  That is actually a good thing. A received consignment has the potential to change the average cost of a product and if that happens we should let all the interested systems know about it.

Now, you are right about race conditions. There is no good way to determine the order in which events were triggered and delivered. We recognise that and that's why we have introduced the concept of versioning in the next iteration of the API. It is primarily used for pagination (http://docs.vend.apiary.io/#introduction/pagination) but the version number on an object can also be used to find out if the event received from the webhook does, in fact, contain the latest version of the resource. The next version of webhooks will also include version numbers.

**Comment by achadee** [comment]
Thanks for that clarification, maybe we are doing something funky with our post requests. I'll review the code later today!

+1 to the versioning that will be awesome
